### ISSUE TITLE
Button Spacing + Names

### ISSUE THREAD

**Issue by heatherlyall** [heatherlyall/button-styles#1]
The buttons for some reason are all squished to one side even though there were spaced out in the middle before. I'm also confused on how to make the different buttons different sizes when some of them are using the same class? @thomasjbradley

Help!

Heather

**Comment by thomasjbradley** [comment]
Have a look at this slide here:
https://learn-the-web.algonquindesign.ca/courses/web-dev-1/link-patterns/#slide-5
Notice how in the HTML the second button has 2 classes on it: `.btn` & `.btn-alt`—it gets all the CSS from `.btn` & all the CSS from `.btn-alt`.

```html
<a class="btn btn-alt">…
```

The buttons are squished because most of them don’t have `display: inline-block`

**Comment by heatherlyall** [comment]
I fixed the squishy part, but I think I might have made the buttons worse... :(  I tried adding the second class and it only seemed to add a button feature beside the original one with none of the features of the first button. @thomasjbradley

**Comment by thomasjbradley** [comment]
Which button did you update? Did you commit & push?

**Comment by heatherlyall** [comment]
I just pushed it oops sorry forgot to do that

**Comment by thomasjbradley** [comment]
Where did you put the 2 classes in the HTML? I can’t seem to find it.

**Comment by heatherlyall** [comment]
It's with the tag btn-subtle right after the Primary button @thomasjbradley

**Comment by thomasjbradley** [comment]
The subtle button should be like this:

```html
<a class="btn btn-subtle">…</a>
```

Where it gets all the CSS from `.btn` but then the only CSS `.btn-subtle` provides is a background colour change.

```css
.btn {
   /* What you have now */
}

.btn-subtle {
  background-color: #ccc;
}
```

**Comment by heatherlyall** [comment]
That's worked for the regular buttons, for the smaller and bigger buttons do I do the same thing except with btn-small instead of btn? @thomasjbradley

**Comment by thomasjbradley** [comment]
Not *instead* of `.btn` but additionally. The `<a>` tags will have 3 classes.

**Comment by heatherlyall** [comment]
Thanks so much that worked!! However why doesn't my ghost button colour border appearing? @thomasjbradley

**Comment by thomasjbradley** [comment]
You are missing: `border-style: solid`

**Comment by heatherlyall** [comment]
Last question because now I only have a 34% difference!! I used the sizes that were given in the Button Styles instructions, but a few of my buttons still seem to be a bit small? How do I fix that @thomasjbradley

**Comment by thomasjbradley** [comment]
Do you have a border on all the buttons?

Every button should have the same size border, just sometimes the border is the same colour as the background colour.

**Comment by heatherlyall** [comment]
That was perfect it's done now!!! thank you so so much :)))))))))) @thomasjbradley
